CCFLAGS  := -Wall -Werror
DBGFLAGS := -D_COLIN_TEST_POLLMGR_ -g
INCLUDE :=
CC		:= g++
LIB 	:= -lpthread
SRC 	:= $(wildcard *.cc)
OBJ		:= $(patsubst %.cc, %.o, $(SRC))
TEST	:= test

all: $(TEST)

$(TEST): $(OBJ)
	$(CC) $(DBGFLAGS) $(CCFLAGS) $(INCLUDE) -o $@ $^ $(LIB)

.cc.o:
	$(CC) $(DBGFLAGS) $(CCFLAGS) $(INCLUDE) -c $<

clean:
	@rm -rf *.o $(TEST)

.phony: clean


